# (3). ndarray - 정렬, 선형대수

## 1. 행렬의 정렬 - sort()와 argsort()

### 1-1. numpy의 sort() 유형

* np.sort(arr): 원 행렬은 그대로 유지, 정렬된 행렬을 반환

* ndarray.sort(): 원 행렬 자체를 정렬한 형태로 변환, 반환값은 None

#### 기본적으로 오름차순으로 정렬한다. [1,2,3,4...]

* 내림차순 정렬하기 -> np.sort()[::-1]




In [1]:
import numpy as np

arr = np.array([3, 1, 9, 5])
print('원본 행렬:', arr)

#np.sort()로 정렬하기
sort_arr = np.sort(arr)
print('np.sort() 호출 후 반환된 정렬 행렬:', sort_arr)
print('np.sort() 호출 후 원본 행렬: ', arr)

#ndarray.sort()로 정렬하기
sort_arr = arr.sort()
arr.sort()
print('arr.sort() 호출 후 반환된 행렬:', sort_arr)
print('arr.sort() 호출 후 원본 행렬:', arr)

원본 행렬: [3 1 9 5]
np.sort() 호출 후 반환된 정렬 행렬: [1 3 5 9]
np.sort() 호출 후 원본 행렬:  [3 1 9 5]
arr.sort() 호출 후 반환된 행렬: None
arr.sort() 호출 후 원본 행렬: [1 3 5 9]


#### 내림차순으로 정렬하기

In [2]:
sort_desc = np.sort(arr)[::-1]
print('내림차순으로 정렬: ', sort_desc)

# arr.sort()[::-1] -> ERROR

내림차순으로 정렬:  [9 5 3 1]


#### axis 방향에 따라 정렬하기

In [3]:
arr2d = np.array([[8, 12],
                 [7, 1]])

# 행 방향으로 정렬
sort_arr = np.sort(arr2d, axis=0)
print('Row 방향으로 정렬:\n', sort_arr)

# 열 방향으로 정렬
sort_arr = np.sort(arr2d, axis=1)
print('Col 방향으로 정렬:\n', sort_arr)

Row 방향으로 정렬:
 [[ 7  1]
 [ 8 12]]
Col 방향으로 정렬:
 [[ 8 12]
 [ 1  7]]


### 1-2. argsort

In [4]:
arr = np.array([3, 1, 9, 5])
print(np.sort(arr))

sort_index = np.argsort(arr)
print(type(sort_index))
print('행렬 정렬 시 원본 행렬의 인덱스:', sort_index)

[1 3 5 9]
<class 'numpy.ndarray'>
행렬 정렬 시 원본 행렬의 인덱스: [1 0 3 2]


In [5]:
print(np.sort(arr)[::-1])

sort_desc = np.argsort(arr)[::-1]
print('행렬 내림차순 정렬 시 원본 행렬의 인덱스:', sort_desc)

[9 5 3 1]
행렬 내림차순 정렬 시 원본 행렬의 인덱스: [2 3 0 1]


### 활용예시:
#### key-value 형태의 데이터를 A=78, B=95, C=84, D=98, E=88 을 ndarray로 표현하고, argsort()를 이용하여 key값을 정렬한다.

Q. 점수를 낮은 순서대로 정렬하여, 그 순서대로 사람 명단을 출력하고 싶을 때?


In [6]:
name = np.array(['A','B','C','D','E'])
score = np.array([78, 95, 84, 98, 88])

#score의 정렬된 값에 해당하는 원본 행렬 위치 인덱스를 반환
sort_index = np.argsort(score)
print("sort indices:", sort_index)

#이를 이용하여 name 행렬에서 해당 순서의 name값 추출. -> Fancy Ind
name_sort =  name[sort_index]
score_sort = score[sort_index]
print(name_sort)
print(score_sort)

sort indices: [0 2 4 1 3]
['A' 'C' 'E' 'B' 'D']
[78 84 88 95 98]


## 2. 선형대수 연산 - 행렬 내적과 전치 행렬

### 2-1. 행렬의 내적

In [7]:
A = np.array([[1,2,3],
             [4,5,6]])

B = np.array([[7,8],
             [9,10],
             [11,12]])

dot_arr = np.dot(A,B)
print('행렬 내적 결과:\n', dot_arr)

행렬 내적 결과:
 [[ 58  64]
 [139 154]]


### 2-2. 전치 행렬

In [8]:
A = np.array([[1,2],
             [3,4]])
trans_mat = np.transpose(A)
print('A의 전치 행렬:\n', trans_mat)

A의 전치 행렬:
 [[1 3]
 [2 4]]
